### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by nazar-pc** [ralexstokes/ssz-rs#51]
I'm a user of a library that has ssz_rs 0.7.0 in dependencies and I'm not able to use it due to yanked crates.
But current 0.8.0 (with a name ssz-rs) while doesn't have this issue, was not released yet.
I'd like to request creating a release, at least pre-release if you plan to include more stuff in here before shipping 0.8.0.

**Comment by ralexstokes** [comment]
hello! thanks for raising this!

i'm actually working towards a v1.0 that i'd consider "feature complete"

that being said, i'm open to a v0.8 (pre-)release soon. 

i'll post here once i have that

**Comment by ralexstokes** [comment]
hi @nazar-pc sorry for the delay here, but I have a `v0.8.0` here: https://github.com/ralexstokes/ssz-rs/releases/tag/v0.8.0

I ran into a compatibility issue with `crates.io` and basically we need to keep the original crate name(s) with underscores instead of dashes -- if you run into issues here I'd be sure to check that when updating
